name = "JuliaLibWrapping"
uuid = "d61f35a8-f6af-436f-bc10-cee6b101f7bd"
version = "0.2.0"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuliaC = "acedd4c2-ced6-4a15-accc-2607eb759ba2"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[extensions]
JuliaLibWrappingJuliaCExt = "JuliaC"

[compat]
Aqua = "0.8"
ExplicitImports = "1.15"
Graphs = "1"
JSON = "0.21.4, 1"
JuliaC = "0.3.10"
Libdl = "1"
OrderedCollections = "1.8.1, 2"
TOML = "1"
Test = "1"
julia = "1.13"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
JuliaC = "acedd4c2-ced6-4a15-accc-2607eb759ba2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ExplicitImports", "JuliaC", "Test"]
