"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "libcstringowned"
_LIBRARY_ENV_VAR = "CSTRING_OWNED_DEMO_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

_JLW_LOADED_ATTR = "_jlw_loaded_packages"
_jlw_loaded = getattr(sys, _JLW_LOADED_ATTR, None)
if _jlw_loaded is None:
    _jlw_loaded = set()
    setattr(sys, _JLW_LOADED_ATTR, _jlw_loaded)
_jlw_this_pkg = __package__ or __name__
if _jlw_loaded and _jlw_this_pkg not in _jlw_loaded:
    import warnings
    warnings.warn(
        f"Loading JuliaLibWrapping-generated package {_jlw_this_pkg!r} into a "
        f"process that already loaded {sorted(_jlw_loaded)!r}. "
        "This package was built without a private libjulia, so both "
        "packages resolve a single Julia runtime and the first call into "
        "whichever did not initialize it aborts the process. Rebuild with "
        "`privatize = true`, or compile both APIs into a single juliac "
        "library. See the JuliaLibWrapping docs section on multiple "
        "wrapped libraries in one process.",
        RuntimeWarning,
        stacklevel=2,
    )
_jlw_loaded.add(_jlw_this_pkg)

def _check_layout(cls, size, offsets):
    actual = (ctypes.sizeof(cls), *(getattr(cls, name).offset for name, _ in cls._fields_))
    if actual != (size, *offsets):
        raise RuntimeError(
            f"{cls.__name__}: ctypes computed (size, *offsets) {actual}, but the "
            f"library was compiled with {(size, *offsets)}; the generated "
            "bindings do not match this platform's ABI"
        )

class CString_owned(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int64),
        ("data", ctypes.POINTER(ctypes.c_uint8)),
    ]

    def as_bytes(self):
        """Return a copy of the underlying bytes as a Python `bytes` object."""
        if not self.data:
            raise RuntimeError("CString_owned has already been freed")
        return ctypes.string_at(self.data, self.length)

    def as_str(self):
        """Return the underlying bytes decoded as UTF-8."""
        if not self.data:
            raise RuntimeError("CString_owned has already been freed")
        return self.as_bytes().decode("utf-8")

    def free(self):
        """Free the Julia-allocated buffer.

        Idempotent: a second call is a no-op. The guard is this struct's own
        `data` field rather than a Python attribute: reading a struct field
        nested in a result yields a fresh wrapper each time, so a flag set on the
        wrapper would be lost, while a field write reaches the shared buffer.
        Freeing nulls `data` and resets the other fields; an accessor
        called afterwards sees the null and raises RuntimeError rather than
        reading the released memory or returning an empty result.

        For callers who bypass the façade's convert-then-free wrapper and talk
        to `_lowlevel` directly."""
        if not self.data:
            return
        _lib.jlw_free(ctypes.cast(self.data, ctypes.c_void_p))
        self.data = type(self.data)()
        self.length = 0
_check_layout(CString_owned, 16, (0, 8))

_lib.give_greeting.argtypes = []
_lib.give_greeting.restype = CString_owned
def give_greeting():
    return _lib.give_greeting()

_lib.jlw_free.argtypes = [ctypes.c_void_p]
_lib.jlw_free.restype = None

_lib.jlw_free_strings.argtypes = [ctypes.POINTER(CString_owned), ctypes.c_int64]
_lib.jlw_free_strings.restype = None

_lib.jlw_free_opaque.argtypes = [ctypes.c_void_p]
_lib.jlw_free_opaque.restype = None

