"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "libcdicti32"
_LIBRARY_ENV_VAR = "CDICT_INT32_DEMO_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

_JLW_LOADED_ATTR = "_jlw_loaded_packages"
_jlw_loaded = getattr(sys, _JLW_LOADED_ATTR, None)
if _jlw_loaded is None:
    _jlw_loaded = set()
    setattr(sys, _JLW_LOADED_ATTR, _jlw_loaded)
_jlw_this_pkg = __package__ or __name__
if _jlw_loaded and _jlw_this_pkg not in _jlw_loaded:
    import warnings
    warnings.warn(
        f"Loading JuliaLibWrapping-generated package {_jlw_this_pkg!r} into a "
        f"process that already loaded {sorted(_jlw_loaded)!r}. "
        "This package was built without a private libjulia, so both "
        "packages resolve a single Julia runtime and the first call into "
        "whichever did not initialize it aborts the process. Rebuild with "
        "`privatize = true`, or compile both APIs into a single juliac "
        "library. See the JuliaLibWrapping docs section on multiple "
        "wrapped libraries in one process.",
        RuntimeWarning,
        stacklevel=2,
    )
_jlw_loaded.add(_jlw_this_pkg)

def _check_layout(cls, size, offsets):
    actual = (ctypes.sizeof(cls), *(getattr(cls, name).offset for name, _ in cls._fields_))
    if actual != (size, *offsets):
        raise RuntimeError(
            f"{cls.__name__}: ctypes computed (size, *offsets) {actual}, but the "
            f"library was compiled with {(size, *offsets)}; the generated "
            "bindings do not match this platform's ABI"
        )

class CString_borrowed(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int64),
        ("data", ctypes.POINTER(ctypes.c_uint8)),
    ]

    @classmethod
    def from_str(cls, s):
        """Return a CString whose buffer holds the UTF-8 encoding of `s`.

        Allocates a fresh ctypes buffer and copies the bytes into it; the
        returned object holds a reference to that buffer, so the caller
        must keep it alive for the duration of any C call that uses it."""
        if not isinstance(s, str):
            raise TypeError(f"expected str, got {type(s).__name__}")
        return cls.from_bytes(s.encode("utf-8"))

    @classmethod
    def from_bytes(cls, b):
        """Return a CString whose buffer holds a copy of the bytes `b`."""
        if not isinstance(b, (bytes, bytearray)):
            raise TypeError(f"expected bytes-like, got {type(b).__name__}")
        n = len(b)
        buf = (ctypes.c_uint8 * n).from_buffer_copy(b) if n else (ctypes.c_uint8 * 0)()
        obj = cls(length=n,
                  data=ctypes.cast(buf, ctypes.POINTER(ctypes.c_uint8)))
        obj._buffer = buf
        return obj

    def as_bytes(self):
        """Return a copy of the underlying bytes as a Python `bytes` object."""
        return ctypes.string_at(self.data, self.length)

    def as_str(self):
        """Return the underlying bytes decoded as UTF-8."""
        return self.as_bytes().decode("utf-8")
_check_layout(CString_borrowed, 16, (0, 8))

class CString_owned(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int64),
        ("data", ctypes.POINTER(ctypes.c_uint8)),
    ]

    def as_bytes(self):
        """Return a copy of the underlying bytes as a Python `bytes` object."""
        if not self.data:
            raise RuntimeError("CString_owned has already been freed")
        return ctypes.string_at(self.data, self.length)

    def as_str(self):
        """Return the underlying bytes decoded as UTF-8."""
        if not self.data:
            raise RuntimeError("CString_owned has already been freed")
        return self.as_bytes().decode("utf-8")

    def free(self):
        """Free the Julia-allocated buffer.

        Idempotent: a second call is a no-op. The guard is this struct's own
        `data` field rather than a Python attribute: reading a struct field
        nested in a result yields a fresh wrapper each time, so a flag set on the
        wrapper would be lost, while a field write reaches the shared buffer.
        Freeing nulls `data` and resets the other fields; an accessor
        called afterwards sees the null and raises RuntimeError rather than
        reading the released memory or returning an empty result.

        For callers who bypass the façade's convert-then-free wrapper and talk
        to `_lowlevel` directly."""
        if not self.data:
            return
        _lib.jlw_free(ctypes.cast(self.data, ctypes.c_void_p))
        self.data = type(self.data)()
        self.length = 0
_check_layout(CString_owned, 16, (0, 8))

class CDict_borrowed_Int32(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int64),
        ("keys", ctypes.POINTER(CString_borrowed)),
        ("values", ctypes.POINTER(ctypes.c_int32)),
    ]

    @classmethod
    def from_dict(cls, d):
        keys = [k.encode("utf-8") for k in d.keys()]
        karr = (CString_borrowed * len(keys))(
            *[CString_borrowed(length=len(b), data=ctypes.cast(ctypes.create_string_buffer(b, len(b)), ctypes.POINTER(ctypes.c_uint8))) for b in keys])
        varr = (ctypes.c_int32 * len(keys))(*d.values())
        obj = cls(length=len(keys),
                  keys=ctypes.cast(karr, ctypes.POINTER(CString_borrowed)),
                  values=ctypes.cast(varr, ctypes.POINTER(ctypes.c_int32)))
        obj._buffer = (keys, karr, varr)
        return obj

    def as_dict(self):
        out = {}
        for i in range(self.length):
            e = self.keys[i]
            k = ctypes.string_at(e.data, e.length).decode("utf-8")
            out[k] = self.values[i]
        return out
_check_layout(CDict_borrowed_Int32, 24, (0, 8, 16))

class CDict_owned_Int32(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int64),
        ("keys", ctypes.POINTER(CString_owned)),
        ("values", ctypes.POINTER(ctypes.c_int32)),
    ]

    def as_dict(self):
        if not self.keys:
            raise RuntimeError("CDict_owned_Int32 has already been freed")
        out = {}
        for i in range(self.length):
            e = self.keys[i]
            k = ctypes.string_at(e.data, e.length).decode("utf-8")
            out[k] = self.values[i]
        return out

    def free(self):
        """Free the Julia-allocated buffers.

        Idempotent: a second call is a no-op. The guard is this struct's own
        `keys` field rather than a Python attribute: reading a struct field
        nested in a result yields a fresh wrapper each time, so a flag set on the
        wrapper would be lost, while a field write reaches the shared buffer.
        Freeing nulls `keys` and resets the other fields; an accessor
        called afterwards sees the null and raises RuntimeError rather than
        reading the released memory or returning an empty result.

        For callers who bypass the façade's convert-then-free wrapper and talk
        to `_lowlevel` directly."""
        if not self.keys:
            return
        _lib.jlw_free_strings(self.keys, self.length)
        _lib.jlw_free(ctypes.cast(self.values, ctypes.c_void_p))
        self.keys = type(self.keys)()
        self.values = type(self.values)()
        self.length = 0
_check_layout(CDict_owned_Int32, 24, (0, 8, 16))

_lib.take_dict_i32.argtypes = [CDict_borrowed_Int32]
_lib.take_dict_i32.restype = ctypes.c_int64
def take_dict_i32(d):
    return _lib.take_dict_i32(d)

_lib.give_dict_i32.argtypes = []
_lib.give_dict_i32.restype = CDict_owned_Int32
def give_dict_i32():
    return _lib.give_dict_i32()

_lib.jlw_free.argtypes = [ctypes.c_void_p]
_lib.jlw_free.restype = None

_lib.jlw_free_strings.argtypes = [ctypes.POINTER(CString_owned), ctypes.c_int64]
_lib.jlw_free_strings.restype = None

_lib.jlw_free_opaque.argtypes = [ctypes.c_void_p]
_lib.jlw_free_opaque.restype = None

