"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib
import numpy as np

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "libctuple"
_LIBRARY_ENV_VAR = "CTUPLE_DEMO_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

_JLW_LOADED_ATTR = "_jlw_loaded_packages"
_jlw_loaded = getattr(sys, _JLW_LOADED_ATTR, None)
if _jlw_loaded is None:
    _jlw_loaded = set()
    setattr(sys, _JLW_LOADED_ATTR, _jlw_loaded)
_jlw_this_pkg = __package__ or __name__
if _jlw_loaded and _jlw_this_pkg not in _jlw_loaded:
    import warnings
    warnings.warn(
        f"Loading JuliaLibWrapping-generated package {_jlw_this_pkg!r} into a "
        f"process that already loaded {sorted(_jlw_loaded)!r}. "
        "This package was built without a private libjulia, so both "
        "packages resolve a single Julia runtime and the first call into "
        "whichever did not initialize it aborts the process. Rebuild with "
        "`privatize = true`, or compile both APIs into a single juliac "
        "library. See the JuliaLibWrapping docs section on multiple "
        "wrapped libraries in one process.",
        RuntimeWarning,
        stacklevel=2,
    )
_jlw_loaded.add(_jlw_this_pkg)

class JLWError(RuntimeError):
    """Raised when a wrapped function returns a non-zero JLWStatus.code."""
    def __init__(self, code, message):
        super().__init__(f"[{code}] {message}")
        self.code = code
        self.message = message

def _check_layout(cls, size, offsets):
    actual = (ctypes.sizeof(cls), *(getattr(cls, name).offset for name, _ in cls._fields_))
    if actual != (size, *offsets):
        raise RuntimeError(
            f"{cls.__name__}: ctypes computed (size, *offsets) {actual}, but the "
            f"library was compiled with {(size, *offsets)}; the generated "
            "bindings do not match this platform's ABI"
        )

class CString_owned(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_uint8)),
    ]

    def as_bytes(self):
        """Return a copy of the underlying bytes as a Python `bytes` object."""
        if not self.data:
            raise RuntimeError("CString_owned has already been freed")
        return ctypes.string_at(self.data, self.length)

    def as_str(self):
        """Return the underlying bytes decoded as UTF-8."""
        if not self.data:
            raise RuntimeError("CString_owned has already been freed")
        return self.as_bytes().decode("utf-8")

    def free(self):
        """Free the Julia-allocated buffer.

        Idempotent: a second call is a no-op. The guard is this struct's own
        `data` field rather than a Python attribute: reading a struct field
        nested in a result yields a fresh wrapper each time, so a flag set on the
        wrapper would be lost, while a field write reaches the shared buffer.
        Freeing nulls `data` and resets the other fields; an accessor
        called afterwards sees the null and raises RuntimeError rather than
        reading the released memory or returning an empty result.

        For callers who bypass the façade's convert-then-free wrapper and talk
        to `_lowlevel` directly."""
        if not self.data:
            return
        _lib.jlw_free(ctypes.cast(self.data, ctypes.c_void_p))
        self.data = type(self.data)()
        self.length = 0
_check_layout(CString_owned, 16, (0, 8))

class CStrArray_owned(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int64),
        ("data", ctypes.POINTER(CString_owned)),
    ]

    def as_list(self):
        if not self.data:
            raise RuntimeError("CStrArray_owned has already been freed")
        out = []
        for i in range(self.length):
            e = self.data[i]
            out.append(ctypes.string_at(e.data, e.length).decode("utf-8"))
        return out

    def free(self):
        """Free the Julia-allocated buffer.

        Idempotent: a second call is a no-op. The guard is this struct's own
        `data` field rather than a Python attribute: reading a struct field
        nested in a result yields a fresh wrapper each time, so a flag set on the
        wrapper would be lost, while a field write reaches the shared buffer.
        Freeing nulls `data` and resets the other fields; an accessor
        called afterwards sees the null and raises RuntimeError rather than
        reading the released memory or returning an empty result.

        For callers who bypass the façade's convert-then-free wrapper and talk
        to `_lowlevel` directly."""
        if not self.data:
            return
        _lib.jlw_free_strings(self.data, self.length)
        self.data = type(self.data)()
        self.length = 0
_check_layout(CStrArray_owned, 16, (0, 8))

class JLWStatus(ctypes.Structure):
    _fields_ = [
        ("code", ctypes.c_int32),
        ("message", (ctypes.c_uint8 * 256)),
    ]
_check_layout(JLWStatus, 260, (0, 4))

class CVector_owned_Float64(ctypes.Structure):
    _fields_ = [
        ("dims", (ctypes.c_int32 * 1)),
        ("data", ctypes.POINTER(ctypes.c_double)),
    ]

    def as_numpy(self):
        """Return a 1-D numpy view of the underlying buffer (no copy)."""
        if not self.data:
            raise RuntimeError("CVector_owned_Float64 has already been freed")
        return np.ctypeslib.as_array(self.data, shape=(self.dims[0],))

    def free(self):
        """Free the Julia-allocated buffer.

        Idempotent: a second call is a no-op. The guard is this struct's own
        `data` field rather than a Python attribute: reading a struct field
        nested in a result yields a fresh wrapper each time, so a flag set on the
        wrapper would be lost, while a field write reaches the shared buffer.
        Freeing nulls `data` and resets the other fields; an accessor
        called afterwards sees the null and raises RuntimeError rather than
        reading the released memory or returning an empty result.

        For callers who bypass the façade's convert-then-free wrapper and talk
        to `_lowlevel` directly."""
        if not self.data:
            return
        _lib.jlw_free(ctypes.cast(self.data, ctypes.c_void_p))
        self.data = type(self.data)()
        self.dims = type(self.dims)()
_check_layout(CVector_owned_Float64, 16, (0, 8))

class Tuple_CVector_owned_Float64_Int64(ctypes.Structure):
    _fields_ = [
        ("_1", CVector_owned_Float64),
        ("_2", ctypes.c_int64),
    ]
_check_layout(Tuple_CVector_owned_Float64_Int64, 24, (0, 16))

class CNTuple_2_Tuple_CVector_owned_Float64_Int64(ctypes.Structure):
    _fields_ = [
        ("values", Tuple_CVector_owned_Float64_Int64),
    ]
_check_layout(CNTuple_2_Tuple_CVector_owned_Float64_Int64, 24, (0,))

class JLWResult_CNTuple_2_Tuple_CVector_owned_Float64_Int64(ctypes.Structure):
    _fields_ = [
        ("status", JLWStatus),
        ("value", CNTuple_2_Tuple_CVector_owned_Float64_Int64),
    ]
_check_layout(JLWResult_CNTuple_2_Tuple_CVector_owned_Float64_Int64, 288, (0, 264))

class CNTuple_2_Tuple_CVector_owned_Float64_CVector_owned_Float64(ctypes.Structure):
    _fields_ = [
        ("values", (CVector_owned_Float64 * 2)),
    ]
_check_layout(CNTuple_2_Tuple_CVector_owned_Float64_CVector_owned_Float64, 32, (0,))

class JLWResult_CNTuple_2_Tuple_CVector_owned_Float64_CVector_owned_Float64(ctypes.Structure):
    _fields_ = [
        ("status", JLWStatus),
        ("value", CNTuple_2_Tuple_CVector_owned_Float64_CVector_owned_Float64),
    ]
_check_layout(JLWResult_CNTuple_2_Tuple_CVector_owned_Float64_CVector_owned_Float64, 296, (0, 264))

class CDict_owned_Float64(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int64),
        ("keys", ctypes.POINTER(CString_owned)),
        ("values", ctypes.POINTER(ctypes.c_double)),
    ]

    def as_dict(self):
        if not self.keys:
            raise RuntimeError("CDict_owned_Float64 has already been freed")
        out = {}
        for i in range(self.length):
            e = self.keys[i]
            k = ctypes.string_at(e.data, e.length).decode("utf-8")
            out[k] = self.values[i]
        return out

    def free(self):
        """Free the Julia-allocated buffers.

        Idempotent: a second call is a no-op. The guard is this struct's own
        `keys` field rather than a Python attribute: reading a struct field
        nested in a result yields a fresh wrapper each time, so a flag set on the
        wrapper would be lost, while a field write reaches the shared buffer.
        Freeing nulls `keys` and resets the other fields; an accessor
        called afterwards sees the null and raises RuntimeError rather than
        reading the released memory or returning an empty result.

        For callers who bypass the façade's convert-then-free wrapper and talk
        to `_lowlevel` directly."""
        if not self.keys:
            return
        _lib.jlw_free_strings(self.keys, self.length)
        _lib.jlw_free(ctypes.cast(self.values, ctypes.c_void_p))
        self.keys = type(self.keys)()
        self.values = type(self.values)()
        self.length = 0
_check_layout(CDict_owned_Float64, 24, (0, 8, 16))

class COpt_Float64(ctypes.Structure):
    _fields_ = [
        ("has_value", ctypes.c_int32),
        ("value", ctypes.c_double),
    ]

    @classmethod
    def from_optional(cls, x):
        if x is None:
            return cls(has_value=0, value=0)
        return cls(has_value=1, value=x)

    def as_optional(self):
        return None if self.has_value == 0 else self.value
_check_layout(COpt_Float64, 16, (0, 8))

class Tuple_CString_owned_CStrArray_owned_CDict_owned_Float64_COpt_Float64(ctypes.Structure):
    _fields_ = [
        ("_1", CString_owned),
        ("_2", CStrArray_owned),
        ("_3", CDict_owned_Float64),
        ("_4", COpt_Float64),
    ]
_check_layout(Tuple_CString_owned_CStrArray_owned_CDict_owned_Float64_COpt_Float64, 72, (0, 16, 32, 56))

class CNTuple_4_Tuple_CString_owned_CStrArray_owned_CDict_owned_Float64_COpt_Float64(ctypes.Structure):
    _fields_ = [
        ("values", Tuple_CString_owned_CStrArray_owned_CDict_owned_Float64_COpt_Float64),
    ]
_check_layout(CNTuple_4_Tuple_CString_owned_CStrArray_owned_CDict_owned_Float64_COpt_Float64, 72, (0,))

class JLWResult_CNTuple_4_Tuple_CString_owned_CStrArray_owned_CDict_owned_Float64_COpt_Float64(ctypes.Structure):
    _fields_ = [
        ("status", JLWStatus),
        ("value", CNTuple_4_Tuple_CString_owned_CStrArray_owned_CDict_owned_Float64_COpt_Float64),
    ]
_check_layout(JLWResult_CNTuple_4_Tuple_CString_owned_CStrArray_owned_CDict_owned_Float64_COpt_Float64, 336, (0, 264))

_lib.stats.argtypes = []
_lib.stats.restype = JLWResult_CNTuple_2_Tuple_CVector_owned_Float64_Int64
def stats():
    _result = _lib.stats()
    if _result.status.code != 0:
        _msg = bytes(_result.status.message).rstrip(b"\x00").decode("utf-8", errors="replace")
        raise JLWError(_result.status.code, _msg)
    return _result

_lib.pair.argtypes = []
_lib.pair.restype = JLWResult_CNTuple_2_Tuple_CVector_owned_Float64_CVector_owned_Float64
def pair():
    _result = _lib.pair()
    if _result.status.code != 0:
        _msg = bytes(_result.status.message).rstrip(b"\x00").decode("utf-8", errors="replace")
        raise JLWError(_result.status.code, _msg)
    return _result

_lib.bundle.argtypes = []
_lib.bundle.restype = JLWResult_CNTuple_4_Tuple_CString_owned_CStrArray_owned_CDict_owned_Float64_COpt_Float64
def bundle():
    _result = _lib.bundle()
    if _result.status.code != 0:
        _msg = bytes(_result.status.message).rstrip(b"\x00").decode("utf-8", errors="replace")
        raise JLWError(_result.status.code, _msg)
    return _result

_lib.jlw_free.argtypes = [ctypes.c_void_p]
_lib.jlw_free.restype = None

_lib.jlw_free_strings.argtypes = [ctypes.POINTER(CString_owned), ctypes.c_int64]
_lib.jlw_free_strings.restype = None

_lib.jlw_free_opaque.argtypes = [ctypes.c_void_p]
_lib.jlw_free_opaque.restype = None

