"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib
import numpy as np

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "mylib"
_LIBRARY_ENV_VAR = "MYLIB_PY_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

_JLW_LOADED_ATTR = "_jlw_loaded_packages"
_jlw_loaded = getattr(sys, _JLW_LOADED_ATTR, None)
if _jlw_loaded is None:
    _jlw_loaded = set()
    setattr(sys, _JLW_LOADED_ATTR, _jlw_loaded)
_jlw_this_pkg = __package__ or __name__
if _jlw_loaded and _jlw_this_pkg not in _jlw_loaded:
    import warnings
    warnings.warn(
        f"Loading JuliaLibWrapping-generated package {_jlw_this_pkg!r} into a "
        f"process that already loaded {sorted(_jlw_loaded)!r}. "
        "This package was built without a private libjulia, so both "
        "packages resolve a single Julia runtime and the first call into "
        "whichever did not initialize it aborts the process. Rebuild with "
        "`privatize = true`, or compile both APIs into a single juliac "
        "library. See the JuliaLibWrapping docs section on multiple "
        "wrapped libraries in one process.",
        RuntimeWarning,
        stacklevel=2,
    )
_jlw_loaded.add(_jlw_this_pkg)

class JLWError(RuntimeError):
    """Raised when a wrapped function returns a non-zero JLWStatus.code."""
    def __init__(self, code, message):
        super().__init__(f"[{code}] {message}")
        self.code = code
        self.message = message

def _check_layout(cls, size, offsets):
    actual = (ctypes.sizeof(cls), *(getattr(cls, name).offset for name, _ in cls._fields_))
    if actual != (size, *offsets):
        raise RuntimeError(
            f"{cls.__name__}: ctypes computed (size, *offsets) {actual}, but the "
            f"library was compiled with {(size, *offsets)}; the generated "
            "bindings do not match this platform's ABI"
        )

class CVector_borrowed_Float64(ctypes.Structure):
    _fields_ = [
        ("dims", (ctypes.c_int64 * 1)),
        ("data", ctypes.POINTER(ctypes.c_double)),
    ]

    @classmethod
    def from_numpy(cls, arr):
        """Return a CArray view of the 1-D numpy array `arr`.

        Raises ValueError on ndim, contiguity, or dtype mismatch (fail-fast: no
        silent reinterpretation). The returned object holds a reference to `arr`,
        so the caller must keep it alive for the duration of any C call that uses
        the buffer."""
        if arr.ndim != 1:
            raise ValueError(f"expected 1-D array, got {arr.ndim}-D")
        if not (arr.flags.c_contiguous or arr.flags.f_contiguous):
            raise ValueError("array must be contiguous")
        expected_dtype = np.dtype("float64")
        if arr.dtype != expected_dtype:
            raise ValueError(f"expected dtype float64, got {arr.dtype}")
        obj = cls(dims=(ctypes.c_int64 * 1)(*arr.shape),
                  data=arr.ctypes.data_as(ctypes.POINTER(ctypes.c_double)))
        obj._buffer = arr
        return obj

    def as_numpy(self):
        """Return a 1-D numpy view of the underlying buffer (no copy)."""
        return np.ctypeslib.as_array(self.data, shape=(self.dims[0],))
_check_layout(CVector_borrowed_Float64, 16, (0, 8))

class CVector_owned_Float64(ctypes.Structure):
    _fields_ = [
        ("dims", (ctypes.c_int64 * 1)),
        ("data", ctypes.POINTER(ctypes.c_double)),
    ]

    def as_numpy(self):
        """Return a 1-D numpy view of the underlying buffer (no copy)."""
        if not self.data:
            raise RuntimeError("CVector_owned_Float64 has already been freed")
        return np.ctypeslib.as_array(self.data, shape=(self.dims[0],))

    def free(self):
        """Free the Julia-allocated buffer.

        Idempotent: a second call is a no-op. The guard is this struct's own
        `data` field rather than a Python attribute: reading a struct field
        nested in a result yields a fresh wrapper each time, so a flag set on the
        wrapper would be lost, while a field write reaches the shared buffer.
        Freeing nulls `data` and resets the other fields; an accessor
        called afterwards sees the null and raises RuntimeError rather than
        reading the released memory or returning an empty result.

        For callers who bypass the façade's convert-then-free wrapper and talk
        to `_lowlevel` directly."""
        if not self.data:
            return
        _lib.jlw_free(ctypes.cast(self.data, ctypes.c_void_p))
        self.data = type(self.data)()
        self.dims = type(self.dims)()
_check_layout(CVector_owned_Float64, 16, (0, 8))

class CString_borrowed(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int64),
        ("data", ctypes.POINTER(ctypes.c_uint8)),
    ]

    @classmethod
    def from_str(cls, s):
        """Return a CString whose buffer holds the UTF-8 encoding of `s`.

        Allocates a fresh ctypes buffer and copies the bytes into it; the
        returned object holds a reference to that buffer, so the caller
        must keep it alive for the duration of any C call that uses it."""
        if not isinstance(s, str):
            raise TypeError(f"expected str, got {type(s).__name__}")
        return cls.from_bytes(s.encode("utf-8"))

    @classmethod
    def from_bytes(cls, b):
        """Return a CString whose buffer holds a copy of the bytes `b`."""
        if not isinstance(b, (bytes, bytearray)):
            raise TypeError(f"expected bytes-like, got {type(b).__name__}")
        n = len(b)
        buf = (ctypes.c_uint8 * n).from_buffer_copy(b) if n else (ctypes.c_uint8 * 0)()
        obj = cls(length=n,
                  data=ctypes.cast(buf, ctypes.POINTER(ctypes.c_uint8)))
        obj._buffer = buf
        return obj

    def as_bytes(self):
        """Return a copy of the underlying bytes as a Python `bytes` object."""
        return ctypes.string_at(self.data, self.length)

    def as_str(self):
        """Return the underlying bytes decoded as UTF-8."""
        return self.as_bytes().decode("utf-8")
_check_layout(CString_borrowed, 16, (0, 8))

class CString_owned(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int64),
        ("data", ctypes.POINTER(ctypes.c_uint8)),
    ]

    def as_bytes(self):
        """Return a copy of the underlying bytes as a Python `bytes` object."""
        if not self.data:
            raise RuntimeError("CString_owned has already been freed")
        return ctypes.string_at(self.data, self.length)

    def as_str(self):
        """Return the underlying bytes decoded as UTF-8."""
        if not self.data:
            raise RuntimeError("CString_owned has already been freed")
        return self.as_bytes().decode("utf-8")

    def free(self):
        """Free the Julia-allocated buffer.

        Idempotent: a second call is a no-op. The guard is this struct's own
        `data` field rather than a Python attribute: reading a struct field
        nested in a result yields a fresh wrapper each time, so a flag set on the
        wrapper would be lost, while a field write reaches the shared buffer.
        Freeing nulls `data` and resets the other fields; an accessor
        called afterwards sees the null and raises RuntimeError rather than
        reading the released memory or returning an empty result.

        For callers who bypass the façade's convert-then-free wrapper and talk
        to `_lowlevel` directly."""
        if not self.data:
            return
        _lib.jlw_free(ctypes.cast(self.data, ctypes.c_void_p))
        self.data = type(self.data)()
        self.length = 0
_check_layout(CString_owned, 16, (0, 8))

class JLWStatus(ctypes.Structure):
    _fields_ = [
        ("code", ctypes.c_int32),
        ("message", (ctypes.c_uint8 * 256)),
    ]
_check_layout(JLWStatus, 260, (0, 4))

class JLWResult_CVector_owned_Float64(ctypes.Structure):
    _fields_ = [
        ("status", JLWStatus),
        ("value", CVector_owned_Float64),
    ]
_check_layout(JLWResult_CVector_owned_Float64, 280, (0, 264))

_lib.mylib_scale.argtypes = [CVector_borrowed_Float64, ctypes.c_double, CString_borrowed]
_lib.mylib_scale.restype = JLWResult_CVector_owned_Float64
def mylib_scale(x, factor, label):
    """Scale every entry."""
    _result = _lib.mylib_scale(x, factor, label)
    if _result.status.code != 0:
        _msg = bytes(_result.status.message).rstrip(b"\x00").decode("utf-8", errors="replace")
        raise JLWError(_result.status.code, _msg)
    return _result

_lib.jlw_free.argtypes = [ctypes.c_void_p]
_lib.jlw_free.restype = None

_lib.jlw_free_strings.argtypes = [ctypes.POINTER(CString_owned), ctypes.c_int64]
_lib.jlw_free_strings.restype = None

_lib.jlw_free_opaque.argtypes = [ctypes.c_void_p]
_lib.jlw_free_opaque.restype = None

